package com.example.backend.model;

public enum Specialization {
    CARDIOLOGY,
    DERMATOLOGY,
    ENDOCRINOLOGY,
    GASTROENTEROLOGY,
    HEMATOLOGY,
    NEUROLOGY,
    ONCOLOGY,
    ORTHOPEDICS,
    PEDIATRICS,
    PSYCHIATRY,
    RADIOLOGY,
    OPHTHALMOLOGY,
    OBSTETRICS_AND_GYNECOLOGY,
    UROLOGY,
    OTOLARYNGOLOGY,
    RHEUMATOLOGY,
    ALLERGY_AND_IMMUNOLOGY,
    EMERGENCY_MEDICINE,
    ANESTHESIOLOGY,
    PULMONOLOGY,
    INFECTIOUS_DISEASE,
    NEPHROLOGY,
    GERIATRICS,
    PHYSICAL_MEDICINE_AND_REHABILITATION,
    SPORTS_MEDICINE
}
